export default function TermsOfService() {
  return (
    <main className="container mx-auto px-4 py-8 md:px-6 bg-background">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
        <p className="mb-4 text-muted-foreground">
          Last updated: October 13, 2025
        </p>
        <p className="mb-4">
          Please read these terms and conditions carefully before using our
          service.
        </p>

        <h2 className="text-2xl font-bold mt-6 mb-2">Acceptance of Terms</h2>
        <p className="mb-4">
          By using Rapitags.online, you agree to be bound by these Terms of
          Service. If you do not agree to these terms, please do not use our
          service.
        </p>

        <h2 className="text-2xl font-bold mt-6 mb-2">Use of the Service</h2>
        <p className="mb-4">
          Our service is designed to help you generate hashtags for your social
          media content. You are responsible for the content you generate and
          how you use it.
        </p>

        <h2 className="text-2xl font-bold mt-6 mb-2">Disclaimer</h2>
        <p className="mb-4">
          The hashtags generated by our service are for informational purposes
          only. We do not guarantee the accuracy or effectiveness of the
          hashtags. The service is provided &quot;as is&quot;, and we are not
          responsible for any outcomes that may result from your use of the
          generated hashtags.
        </p>

        <h2 className="text-2xl font-bold mt-6 mb-2">Changes to These Terms</h2>
        <p className="mb-4">
          We may update these Terms of Service from time to time. We will notify
          you of any changes by posting the new Terms of Service on this page.
        </p>

        <h2 className="text-2xl font-bold mt-6 mb-2">Contact Us</h2>
        <p className="mb-4">
          If you have any questions about these Terms of Service, you can
          contact us by visiting this page on our website:{" "}
          <a
            href="https://vikramsamak.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            https://vikramsamak.com
          </a>
        </p>
      </div>
    </main>
  );
}
